### PR TITLE
Notransients

### PR DESCRIPTION
**Pull request by sbird**
This moves the things in the union{} to their respective modules.

### CODE REVIEW

**Comment by sbird** [comment]
> This can be done, because petapm does not exchange particles or permute particles. thus, RegionInd is stable.
> Am I correct on this assertion?

Yes, that is exactly right. All communication is done at the Pencil level.

**Comment by sbird** [comment]
> I recall this may corrupt snapshots can contain wrong GrNr ; does it not?

I will check. I remember the problem you're thinking of, and I think it has been fixed by refactorings.

**Comment by sbird** [comment]
Confirmed this makes no difference to FOF or particle output

**Comment by sbird** [comment]
and is very slightly faster (but not a lot)

**Comment by rainwoodman** [comment]
And even in force calculation particles do not move in memory locations. The copy / reduce function takes care of packing P and non-P data fields during communication.

Besides GC and Domain, any other component changes the memory location of particles?

**Comment by sbird** [comment]
That's right. I don't believe anything else changes the memory location of the particles - this is anyway an invalid operation when the tree is allocated.

**Pull request merged**
