### PR TITLE
Added PrimordialRunning to MP-GenIC and make_class_power.py

### PR DESCRIPTION
**Pull request by Chris-Pedersen**
As mentioned in #255

### CODE REVIEW

**Comment by sbird** [comment]
I'm not so sure about this - really what it is doing is adjusting the class power spectrum generation, and the GenIC changes are just because GenIC uses the same paramfile. In general I'd prefer to keep make_class_power.py minimal and have people with more complex cosmologies just roll their own power spectra (which I already do in my emulator code). However, this is just one extra parameter and is fairly generic, so I could probably live with it if you are really attached to keeping make_class_power.py.

Yu, what do you think?

**Comment by rainwoodman** [comment]
@Chris-Pedersen, I think we'll at least need to add 'ignored for tabulated data' in the help string.

The problem is we already have the PrimordialIndex argument there to invite new parameters like this. So we shall either drop both, or include both.

Any capacity in the existing code is likely treated by new coming developers as mandatory rather than coincidental, regardless of the original intent.

**Comment by Chris-Pedersen** [comment]
Whatever you guys feel is best! We can keep this on our own branch if that's best.

**Comment by rainwoodman** [comment]
My vote is to add this.

**Comment by sbird** [comment]
Ok, then merge it!

**Comment by sbird** [comment]
but with a fixed help string saying that the parameter is unused and only for make_class_power.py

**Comment by Chris-Pedersen** [comment]
Ok I've modified the parameter string.

**Comment by sbird** [comment]
Looks good merge it from me.

**Comment by sbird** [comment]
Oh wait...Chris does not have the power to merge. I will do it when travis goes green.

**Pull request merged**
