### PR TITLE
Drift BH to halo center more aggressively.

### PR DESCRIPTION
**Pull request by sbird**
Disable the sound speed check for black hole drift, as is done in bluetides-ii. We suspect it is causing the BH to drift away from the halo center.

### CODE REVIEW

**Comment by rainwoodman** [comment]
I don't think we shall drift BH by the velocity in drift.c, neither.

At one point I was convinced to add that, but last Wedensday talking to Yueyin I realized the velocity based drift  is essentially drifting with the velocity of a random particle in the halo -- and it means the BH is moving thermally in the halo instead of drifting to the center.

**Comment by sbird** [comment]
That makes sense - I think you are right about the random drifting. There is the added complication that the accelerations for the BH are computed before the BH is repositioned, so it is also receiving essentially a random kick to its velocity. We should probably reposition and set the velocity to the gradient of the potential or something.

**Comment by sbird** [comment]
Also by moving the BH in blackhole.c we ensure that the bh feedback actually applies to the center of the halo.

**Comment by rainwoodman** [comment]
except we shall not move any particles during tree walk...

Yu

**Comment by rainwoodman** [comment]
Let's merge this!

**Comment by sbird** [comment]
It works, but I would like to tidy it up a bit before merging. I will add a comment about the tree breaking, although it is safe in this specific case because BH do not participate in the wind treewalk.

**Comment by rainwoodman** [comment]
I see. Becasue this is the last time we use the tree on BH, it is OK to
break their tree invariance here.

We can probably remove the drifting logic from drift.c then.

**Comment by sbird** [comment]
Any preferences about whether or not we keep the black hole sound speed check? Yueying says it works fine without it and it is an extra model complexity so I am tempted not to.

**Comment by rainwoodman** [comment]
I didnt think it makes sense to check for sound speed with DM particles.

A bounding energy check is more reasonable if worried about pathelogical
cases.

So I vote for removal.

**Comment by sbird** [comment]
Passed unanimously!

**Comment by sbird** [comment]
Aha I see why the old code was not working at all! It is more simple than we thought. The black hole code should have been doing:

treewalk_preprocess() {
MinPotPos = Pos
}

treewalk_reduce(){
if(MinPot > Potential(neighbours)
MinPot = Potential(neighbours)
MinPotPos = Position(neighbours)
}

but it was actually doing:
treewalk_reduce(){
if(MinPot > Potential(neighbours)
MinPot = Potential(neighbours)
MinPotPos = Position(neighbours)
}

treewalk_preprocess() {
MinPotPos = Pos
}
because the preprocess function is treewalk_feedback_preprocess instead of treewalk_accretion_preprocess! So MinPotPos was always being over-written with the current position! 

hoho. We could reposition in drift.c if we wanted to with this fixed.

Should we?

**Comment by sbird** [comment]
See this PR https://github.com/MP-Gadget/MP-Gadget/pull/328 which is the root cause.

**Comment by rainwoodman** [comment]
Aha! That was it!

Yes drifting in drifting.c is way cleaner than drifting in treewalk.

**Comment by sbird** [comment]
It is, but I am concerned because it *is* a BH model change. If we are to do it for real I would like to remove the "induced star formation" stuff at the same time and just check the star formation rates are roughly correct at z=0 once.

**Pull request closed without merging**
