### PR TITLE
Bhdetails

### PR DESCRIPTION
**Pull request by rainwoodman**
This PR dumps more information about the blackholes and do so at every time step. The output is one binary file per rank.

### CODE REVIEW

**Comment by rainwoodman** [comment]
Yes it will go to master as well. 
I indeed have recently added a `grow` interface to bigfile, with supporting this use case in mind.
The reason for not using bigfile is because this happens every time step, and I worry bigfile is too slow for this -- opening and closing many disk files frequently.

**Comment by sbird** [comment]
You should probably check that bigfile is too slow...it is a serious usability problem to have multiple output formats, and if we can avoid it we should. If this is intended for debugging only then we should be ok as well.

**Comment by rainwoodman** [comment]
Creating a file can take the order of 1 second on a busy lustre. Then each
data block is at least 3 files.

I think the proper way to write to any storage model that is not one file
per rank is going to be
an infrastructure for collecting / buffering the output, and
notifying the caller for writing collectively when any of the local buffer
is going to be full.

This shall probably go into bigfile, as an extension to the BigArray
interface.

Will there be other use cases than BH details?

**Comment by sbird** [comment]
I think a separate on-disc format is fine if needed as long as the bigfile python routine can read it.

Stars as well as BH would be useful. I was also considering extending the code to allow outputting struct state_of_system on every timestep in an easier format. Plus at some point I wanted to dump selected particles every timestep, which this could be used for.

**Comment by sbird** [comment]
Since this is going to bluetides-ii and we clearly didn't get the time to implement the more general code, do you want to just merge this?

**Comment by sbird** [comment]
Dropping because Yueying cleaned it up and merged something similar.

**Pull request closed without merging**
