### PR TITLE
Internalmpsort

### PR DESCRIPTION
**Pull request by sbird**
This copies MP-Sort to an internal MP-Gadget location, runs the tests automatically and uses MP-Gadget infrastructure.

### CODE REVIEW

**Comment by sbird** [comment]
It includes https://github.com/rainwoodman/MP-sort/pull/5

**Comment by sbird** [comment]
Ok, this has made the hang reproduce on travis! Progress!

**Comment by sbird** [comment]
Backtrace:
#0  0x00007feb5def6cd8 in pthread_mutex_lock () from /lib64/libpthread.so.0
#1  0x00007feb586c1f14 in ompi_coll_libnbc_progress () from /usr/lib64/openmpi/lib/openmpi/mca_coll_libnbc.so
#2  0x00007feb5d9c4784 in opal_progress () from /usr/lib64/openmpi/lib/libopen-pal.so.40
#3  0x00007feb5d9cb1c5 in ompi_sync_wait_mt () from /usr/lib64/openmpi/lib/libopen-pal.so.40
#4  0x00007feb5df95d6e in ompi_request_default_wait () from /usr/lib64/openmpi/lib/libmpi.so.40
#5  0x00007feb5dff46bc in ompi_coll_base_sendrecv_actual () from /usr/lib64/openmpi/lib/libmpi.so.40
#6  0x00007feb5dff4a83 in ompi_coll_base_allreduce_intra_recursivedoubling () from /usr/lib64/openmpi/lib/libmpi.so.40
#7  0x00007feb5dfa9ead in PMPI_Allreduce () from /usr/lib64/openmpi/lib/libmpi.so.40
#8  0x00000000004cfd91 in mpsort_mpi_histogram_sort (d=..., o=..., tmr=0x736240 <_TIMERS+416>) at utils/mpsort.c:1036
#9  0x00000000004ce141 in mpsort_mpi_newarray_impl (mybase=0x7feb51385800, mynmemb=0, myoutbase=0x7feb51385800, myoutnmemb=0, 
    elsize=40, radix=0x4142c2 <fof_radix_Group_OriginalTaskMinID>, rsize=16, arg=0x0, comm=0x731580 <ompi_mpi_comm_world>, 
    line=1023, file=0x6c6fe0 "fof.c") at utils/mpsort.c:880
#10 0x00000000004cd418 in mpsort_mpi_impl (mybase=0x7feb51385800, mynmemb=0, size=40, 
    radix=0x4142c2 <fof_radix_Group_OriginalTaskMinID>, rsize=16, arg=0x0, comm=0x731580 <ompi_mpi_comm_world>, line=1023, 
    file=0x6c6fe0 "fof.c") at utils/mpsort.c:737

#0  0x00007fdef623b2a8 in __pthread_mutex_unlock_usercnt () from /lib64/libpthread.so.0
#1  0x00007fdef0a0aebd in ompi_coll_libnbc_progress () from /usr/lib64/openmpi/lib/openmpi/mca_coll_libnbc.so
#2  0x00007fdef5d07784 in opal_progress () from /usr/lib64/openmpi/lib/libopen-pal.so.40
#3  0x00007fdef5d0e1c5 in ompi_sync_wait_mt () from /usr/lib64/openmpi/lib/libopen-pal.so.40
#4  0x00007fdef62d8d6e in ompi_request_default_wait () from /usr/lib64/openmpi/lib/libmpi.so.40
#5  0x00007fdef63376bc in ompi_coll_base_sendrecv_actual () from /usr/lib64/openmpi/lib/libmpi.so.40
#6  0x00007fdef6337a83 in ompi_coll_base_allreduce_intra_recursivedoubling () from /usr/lib64/openmpi/lib/libmpi.so.40
#7  0x00007fdef62ecead in PMPI_Allreduce () from /usr/lib64/openmpi/lib/libmpi.so.40
#8  0x00000000004cfe1f in mpsort_mpi_histogram_sort (d=..., o=..., tmr=0x736240 <_TIMERS+416>) at utils/mpsort.c:1038
#9  0x00000000004ce141 in mpsort_mpi_newarray_impl (mybase=0x7fdedfa80800, mynmemb=0, myoutbase=0x7fdedfa80800, myoutnmemb=0, 
    elsize=40, radix=0x4142c2 <fof_radix_Group_OriginalTaskMinID>, rsize=16, arg=0x0, comm=0x731580 <ompi_mpi_comm_world>, 
    line=1023, file=0x6c6fe0 "fof.c") at utils/mpsort.c:880
#10 0x00000000004cd418 in mpsort_mpi_impl (mybase=0x7fdedfa80800, mynmemb=0, size=40, 
    radix=0x4142c2 <fof_radix_Group_OriginalTaskMinID>, rsize=16, arg=0x0, comm=0x731580 <ompi_mpi_comm_world>, line=1023, 
    file=0x6c6fe0 "fof.c") at utils/mpsort.c:737

**Comment by sbird** [comment]
Notice that in one task it is in the Allreduce on line 1038, in the other the one on line 1036. Must be memory corruption somewhere.

**Comment by rainwoodman** [comment]
Add a barrier and printf at Line 1031, or reenable the if 0 section may reveal why the ranks are out of sync.

Which test case is breaking this?

It could be broken sync between test cases, e.g. if some cases run on a single rank and some run on multiple -- especially if this goes away when you run just the broken test case.

**Comment by sbird** [comment]
So a bit of further debugging revealed that this is *not* a hanging Allreduce: each Allreduce completes fine, but the code is stuck in an endless while() loop doing the bisection of Piter (mpsort-mpi.c:630).
This seems to happen because it has Pmin = {-1, -1, -1} and Pmax = {0, 0, 0}, while after the first iteration P = {-2, -1, -1} and the bisection never ends.

**Comment by sbird** [comment]
This looks like some sort of odd overflow behaviour in the bisect or radix functions?

**Comment by sbird** [comment]
@rainwoodman : The current test case for MP-Sort uses a large radix and the FOF radix function and fails if NTask >=8 on my workstation. Can you take a look? I ran with optimizations off and the undefined behaviour and address sanitizers, which were clean for that test. This has to be a bug in MP-Sort, I think.

**Comment by sbird** [comment]
Merging this!

**Pull request merged**
