### PR TITLE
Add parameter to rescale hydrogen heat amplitude

### PR DESCRIPTION
**Pull request by Chris-Pedersen**
There might be a neater way to implement this, let me know what you think.

### CODE REVIEW

**Comment by sbird** [comment]
I'm happy with the implementation, but please fix the tests.

**Comment by Chris-Pedersen** [comment]
Ok will do!

**Comment by Chris-Pedersen** [comment]
Had to take the log out of the loop as it was breaking some tests, probably faster this way. This should go green now.

**Comment by sbird** [comment]
Can you explicitly set CoolingParams.HydrogenHeatAmp = 0 in both test_cooling.c and test_cooling_rates.c? Just to be safe. Then I will merge.

**Pull request merged**
