### PR TITLE
Texatweaks

### PR DESCRIPTION
**Pull request by sbird**
Tweaks inspired by the texascale day.

### CODE REVIEW

**Comment by sbird** [comment]
@yyang440 Can you check that this version builds and runs on Mac?

**Comment by astro-YYH** [comment]
Yes, it successfully built and ran on my macbook (ARM architecture)!

**Comment by astro-YYH** [comment]
Yes, I have 'OPT += -DNO_OPENMP_SPINLOCK' enabled in Option.mk, do I need to also test without this flag?

**Comment by sbird** [comment]
Why not? It is a flag added only for Mac, would be nice if it is no longer needed.

**Comment by astro-YYH** [comment]
Looks like it failed to build without the flag:

`utils/spinlocks.c:14:5: error: unknown type name 'pthread_spinlock_t'; did you mean 'pthread_rwlock_t'?
   14 |     pthread_spinlock_t * SpinLocks;
      |     ^~~~~~~~~~~~~~~~~~
      |     pthread_rwlock_t
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_pthread/_pthread_rwlock_t.h:31:35: note: 'pthread_rwlock_t' declared here
   31 | typedef __darwin_pthread_rwlock_t pthread_rwlock_t;
      |                                   ^
utils/spinlocks.c:25:5: error: call to undeclared function 'pthread_spin_lock'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   25 |     pthread_spin_lock(&spin->SpinLocks[i]);
      |     ^
utils/spinlocks.c:25:5: note: did you mean 'pthread_mutex_lock'?
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/pthread.h:393:5: note: 'pthread_mutex_lock' declared here
  393 | int pthread_mutex_lock(pthread_mutex_t *);
      |     ^
utils/spinlocks.c:32:5: error: call to undeclared function 'pthread_spin_unlock'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   32 |     pthread_spin_unlock(&spin->SpinLocks[i]);
      |     ^
utils/spinlocks.c:32:5: note: did you mean 'pthread_mutex_unlock'?
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/pthread.h:405:5: note: 'pthread_mutex_unlock' declared here
  405 | int pthread_mutex_unlock(pthread_mutex_t *);
      |     ^
utils/spinlocks.c:41:12: error: call to undeclared function 'pthread_spin_trylock'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   41 |     return pthread_spin_trylock(&spin->SpinLocks[i]);
      |            ^
utils/spinlocks.c:41:12: note: did you mean 'pthread_mutex_trylock'?
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/pthread.h:401:5: note: 'pthread_mutex_trylock' declared here
  401 | int pthread_mutex_trylock(pthread_mutex_t *);
      |     ^
utils/spinlocks.c:54:43: error: expected expression
   54 |     spin.SpinLocks = (pthread_spinlock_t *) mymalloc("SpinLocks", NumLock * sizeof(pthread_spinlock_t));
      |                                           ^
utils/spinlocks.c:54:23: error: use of undeclared identifier 'pthread_spinlock_t'
   54 |     spin.SpinLocks = (pthread_spinlock_t *) mymalloc("SpinLocks", NumLock * sizeof(pthread_spinlock_t));
      |                       ^
utils/spinlocks.c:61:9: error: call to undeclared function 'pthread_spin_init'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   61 |         pthread_spin_init(&spin.SpinLocks[i], PTHREAD_PROCESS_PRIVATE);
      |         ^
utils/spinlocks.c:75:9: error: call to undeclared function 'pthread_spin_destroy'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   75 |         pthread_spin_destroy(&(spin->SpinLocks[i]));
      |         ^
8 errors generated.
make[1]: *** [.objs/utils/spinlocks.o] Error 1`

**Comment by sbird** [comment]
Ok, then we keep those for now. This speeds up the code by 2% on the small hydro benchmark, no change to output.

**Comment by astro-YYH** [comment]
Yes, seems we should keep it still!

**Comment by sbird** [comment]
And it works on the threaded code too. Merging!

**Pull request merged**
