### PR TITLE
fix a corruption in sfr_eff when MyFloat is not double

### PR DESCRIPTION
**Pull request by rainwoodman**

### CODE REVIEW

**Comment by sbird** [comment]
Oops, this is because I used a temporary double in get_neutral_fraction_sfreff ?

**Comment by sbird** [comment]
It isn't actually necessary to set ne_new on entry: it is never read. get_starformation_rate_full reads SPHP(i).Ne into a temporary double itself.

**Comment by rainwoodman** [comment]
Indeed. I fixed another warning related to this as well. Hope it didn't affect any runs? (if MyFloat is set to float it would trigger undefined values)

**Comment by sbird** [comment]
I don't think so. I haven't made a run with MyFloat == float for a while. Thanks for the fix

**Comment by sbird** [comment]
(just to be explicit: feel free to merge!)

**Pull request merged**
