### PR TITLE
allow to softening the effective equation of state

### PR DESCRIPTION
**Pull request by yueyingn**
Hi Simeon, I will have a run testing softening the equation of state. Can you check if the modification like this make sense?

### CODE REVIEW

**Comment by yueyingn** [comment]
Sorry this PR messed up with some other commits. I will make a clean PR after tested.

**Comment by sbird** [comment]
Thanks @yueyingn - that looks right to me (once the int->int64 is fixed). I would hope that this makes very little difference to star formation but fingers crossed it speeds up the code!

**Comment by sbird** [comment]
We decided not to use this - shall we merge it anyway? It does no harm and is a not unreasonable feature to have.

**Comment by yueyingn** [comment]
How about just drop it? It does no harm but also no use and makes the code longer. I don't expect we are going to revisit it in the near future. Up to you though!

**Comment by sbird** [comment]
It's your code so your decision and I will drop it :)

**Pull request closed without merging**
