### PR TITLE
Update bigfile

### PR DESCRIPTION
**Pull request by rainwoodman**
A typo fix, and a refactoring of the grouping routines.

### CODE REVIEW

**Comment by sbird** [comment]
I don't really know the code, but looks ok to me

**Comment by rainwoodman** [comment]
Yes. Let's hope there are no more silly typos. There was a bug when number of ranks > 2^16 in this version that got discovered in one of the large runs. It is substantially faster (a factor of 10) than the old version for small files (e.g. stars).

**Comment by sbird** [comment]
What machine are you running on that has > 2^16 ranks?

**Comment by rainwoodman** [comment]
Cori. 65536 if I use 1024 nodes.

**Comment by rainwoodman** [comment]
It was FastPM, so I do not need to worry about the tree preferring threads over ranks.

**Comment by sbird** [comment]
Ah, I see. Makes sense. You run on KNL with 1 rank per physical core and don't use the hyperthreading?

**Comment by rainwoodman** [comment]
Sort of.

The optimal setting was 64x4. 64x2 is within error margin. 128x2 was
noticeably slower, for whatever reason.

**Comment by sbird** [comment]
Thanks

**Pull request merged**
