### PR TITLE
Noglobalsort

### PR DESCRIPTION
**Pull request by sbird**
This PR force-disables gather sort in MP-Sort, which has problems with icc, and by default doesn't use MP-Sort during the domain decomposition. It also modifies domain so it handles uneven particle distributions with garbage better.

### CODE REVIEW

**Comment by sbird** [comment]
This hangs on stampede (mvapich) with the following backtrace:
#0  0x00002b505138ecc1 in amsh_poll () from /lib64/libpsm2.so.2
#1  0x00002b50513ac2b7 in psm2_poll () from /lib64/libpsm2.so.2
#2  0x00002b504d27a2f3 in MPIDI_CH3_Progress_start (pstate=0x1a6c740) at src/mpid/ch3/channels/psm/src/mpidi_calls.c:190
#3  0x00002b504d1e7004 in MPIC_Wait (request_ptr=0x1a6c740, errflag=0x0) at src/mpi/coll/helper_fns.c:293
#4  0x00002b504d1e6df2 in MPIC_Sendrecv (sendbuf=0x1a6c740, sendcount=0, sendtype=1423277376, dest=0, sendtag=0, 
    recvbuf=0x7fffeeabe3d0, recvcount=1, recvtype=1275069445, source=1, recvtag=14, comm_ptr=0x2b575fc54470, status=0x1, 
    errflag=0x7fffeeabe3d4) at src/mpi/coll/helper_fns.c:556
#5  0x00002b504d115628 in MPIR_Allreduce_pt2pt_rd_MV2 (sendbuf=0x1a6c740, recvbuf=0x0, count=1293913024, datatype=3, 
    op=0, comm_ptr=0x7fffeeabe3d0, errflag=0x7fff4c000405) at src/mpi/coll/allreduce_osu.c:395
#6  0x00002b504d112cd0 in MPIR_Allreduce_index_tuned_intra_MV2 (sendbuf=0x1a6c740, recvbuf=0x0, count=1423277376, 
    datatype=0, op=0, comm_ptr=0x7fffeeabe3d0, errflag=0x4) at src/mpi/coll/allreduce_osu.c:2602
#7  0x00002b504d0a5555 in MPIR_Allreduce_impl (sendbuf=0x1a6c740, recvbuf=0x0, count=1423277376, datatype=0, op=0, 
    comm_ptr=0x7fffeeabe3d0, errflag=0x7fffeeabe3d0) at src/mpi/coll/allreduce.c:771
#8  0x00002b504d16a60b in create_2level_comm (comm=27707200, size=0, my_rank=1423277376)
    at src/mpi/comm/create_2level_comm.c:1022
#9  0x00002b504d13837c in mv2_increment_allgather_coll_counter (comm_ptr=0x1a6c740) at src/mpi/coll/ch3_shmem_coll.c:1917
#10 0x00002b504d0a4dc1 in PMPI_Allreduce (sendbuf=0x1a6c740, recvbuf=0x0, count=1423277376, datatype=0, op=0, 
    comm=-290724912) at src/mpi/coll/allreduce.c:919
#11 0x0000000000490089 in mpsort_mpi_histogram_sort (d=..., o=..., tmr=0x1a6c740) at mpsort-mpi.c:579
#12 0x000000000048f298 in mpsort_mpi_newarray (mybase=<optimized out>, mynmemb=0, myoutbase=<optimized out>, 
    myoutnmemb=0, elsize=<optimized out>, radix=<optimized out>, rsize=<optimized out>, arg=<optimized out>, 
    comm=<optimized out>) at mpsort-mpi.c:403
#13 mpsort_mpi (mybase=0x1a6c740, mynmemb=0, size=47624020655424, radix=0x0, rsize=0, arg=0x7fffeeabe3d0, 
    comm=1140850688) at mpsort-mpi.c:290
#14 0x000000000041c70f in fof_assign_grnr (base=0x2b505b553000, NgroupsExt=0, Comm=1140850688) at fof.c:992
#15 0x0000000000418389 in fof_fof (tree=0x7fffeeabf120, BoxSize=4000, BlackHoleInfo=1, Comm=1140850688) at fof.c:199
#16 0x000000000043a934 in run (RestartSnapNum=-1) at run.c:232
#17 0x0000000000408043 in main (argc=2, argv=0x7fffeeabf308) at main.c:128
(gdb) quit
A debugging session is active.

**Comment by sbird** [comment]
I think I discovered the source of those mysterious FoF problems we have long suspected...

**Comment by rainwoodman** [comment]
Misaligned call to MPI_Allreduce?

**Comment by sbird** [comment]
It is not misaligned, but it is part of a rather large stack allocation, and the mpsort_mpi call does have a particularly large radix, 24 bytes.

**Pull request merged**
